// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXOUjB3wHIiq-_00JTgd6yenPQ48i99io',
    appId: '1:530223897969:web:89d6729218299ec03eaad0',
    messagingSenderId: '530223897969',
    projectId: 'henloapp-2def2',
    authDomain: 'henloapp-2def2.firebaseapp.com',
    storageBucket: 'henloapp-2def2.firebasestorage.app',
    measurementId: 'G-6G027Y178Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjNV5f81IPG4ai7kQTHkEMwvwwkaWtG18',
    appId: '1:530223897969:android:f5671c83607dce473eaad0',
    messagingSenderId: '530223897969',
    projectId: 'henloapp-2def2',
    storageBucket: 'henloapp-2def2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp13jqsCPR30gYEJ-5YoLhWZ15xsmFjBs',
    appId: '1:530223897969:ios:1ffb463bd7c380f33eaad0',
    messagingSenderId: '530223897969',
    projectId: 'henloapp-2def2',
    storageBucket: 'henloapp-2def2.firebasestorage.app',
    iosBundleId: 'com.example.petapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp13jqsCPR30gYEJ-5YoLhWZ15xsmFjBs',
    appId: '1:530223897969:ios:1ffb463bd7c380f33eaad0',
    messagingSenderId: '530223897969',
    projectId: 'henloapp-2def2',
    storageBucket: 'henloapp-2def2.firebasestorage.app',
    iosBundleId: 'com.example.petapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXOUjB3wHIiq-_00JTgd6yenPQ48i99io',
    appId: '1:530223897969:web:b295826128d97ec43eaad0',
    messagingSenderId: '530223897969',
    projectId: 'henloapp-2def2',
    authDomain: 'henloapp-2def2.firebaseapp.com',
    storageBucket: 'henloapp-2def2.firebasestorage.app',
    measurementId: 'G-GGVNSN5L96',
  );
}
